Fixed bug with multiple values under the same key
jeremybrooks/knicker pull request #5
Opened 2017-07-22 02:19 UTC by albertopoljak

Method buildParamList generated inncorect URL when there were multiple
values under the same key.
For instance variable excludePartOfSpeech was broken when trying to add
multiple exclusions.

2020-10-13 16:46 UTC, jeremybrooks reviewed
Wow, missed this one. :-) 

I think it can be written as 
`
for (String part : params.get(key).split("\\,")) {
  sb.append(URLEncoder.encode(key, "UTF-8")).append('=').append(URLEncoder.encode(part, "UTF-8")).append('&');
}`

I'll make the change in the develop branch and it will be in the next release. Thanks.

2020-10-13 17:08 UTC, jeremybrooks requested changes

2020-10-13 17:08 UTC, jeremybrooks commented on src/main/java/net/jeremybrooks/knicker/Util.java
>  			} catch (Exception e) {
Using this in develop:
`				for (String part : params.get(key).split("\\,")) {
          sb.append(URLEncoder.encode(key, "UTF-8")).append('=').append(URLEncoder.encode(part, "UTF-8")).append('&');
        }`

2020-10-19 15:10 UTC, albertopoljak commented
Oof I thought I've forgot Java by now and would have no idea what's this about anymore.
But it's pretty simple and your changes are better, thank you for reviewing - better late than never :)

I'll close this as it's already committed in dev branch.

2020-10-19 15:10 UTC, closed without merging